# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

Pod::Spec.new do |s|
  s.name             = 'CoreFramework'
  s.version.         = '1.0.0'
  s.summary          = 'Um frame para utilizar como core de design para Reminder'
  s.description.     = <<-DESC
      Onboarding, Toggle de favoritos e avaliar na loja, além de um design completo


end
